# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Workshop Description
    url: '#description'
    weight: 10
  - name: Shared Task
    url: '#shared-task'
    weight: 20
  - name: Workshop Topics
    url: '#topics'
    weight: 30
  - name: Paper Types and Formats
    url: '#paper-format'
    weight: 40
  - name: Important Dates
    url: '#dates'
    weight: 50
  - name: Submission
    url: '#submission'
    weight: 60 
  - name: Committees
    url: '#committees'
    weight: 75
  - name: Accepted Papers
    url: '#accepted-papers'
    weight: 65 
  - name: Workshop Program
    url: '#workshop-program'
    weight: 80
  - name: Previous Proceedings
    url: https://scholar.google.com/citations?user=YmKaJR4AAAAJ&hl=en&authuser=2
    weight: 90
  # - name: OSACT5
  #   url: https://OSACT5-LREC.github.io
  #   weight: 85
  # Dropdown menu
  - name: Previous Workshops
    url: '#'
    weight: 85
    identifier: previous-workshops

  - name: OSACT 5 (LREC 2022)
    url: https://osact5-lrec.github.io
    parent: previous-workshops
    weight: 2

  - name: OSACT 6 (LREC 2024)
    url: 'https://osact6-lrec.github.io/'
    parent: previous-workshops
    weight: 1
     
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
